// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIf0QSefxUIhp80Nso0FSv_JtCW7AQym0',
    appId: '1:32212048936:web:a4d2e9fc26ff62e4cca91d',
    messagingSenderId: '32212048936',
    projectId: 'partymanagement-3e485',
    authDomain: 'partymanagement-3e485.firebaseapp.com',
    storageBucket: 'partymanagement-3e485.firebasestorage.app',
    measurementId: 'G-DVR1C59NPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvUtPLTD9-OogPH62rpdpREwdeqUN-qlI',
    appId: '1:32212048936:android:56398794a669fb6ccca91d',
    messagingSenderId: '32212048936',
    projectId: 'partymanagement-3e485',
    storageBucket: 'partymanagement-3e485.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe56USfvmRtQjTUttg_ygJJivpPUY81F8',
    appId: '1:32212048936:ios:0599238430ca6e12cca91d',
    messagingSenderId: '32212048936',
    projectId: 'partymanagement-3e485',
    storageBucket: 'partymanagement-3e485.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe56USfvmRtQjTUttg_ygJJivpPUY81F8',
    appId: '1:32212048936:ios:0599238430ca6e12cca91d',
    messagingSenderId: '32212048936',
    projectId: 'partymanagement-3e485',
    storageBucket: 'partymanagement-3e485.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIf0QSefxUIhp80Nso0FSv_JtCW7AQym0',
    appId: '1:32212048936:web:5ae7f272e335991fcca91d',
    messagingSenderId: '32212048936',
    projectId: 'partymanagement-3e485',
    authDomain: 'partymanagement-3e485.firebaseapp.com',
    storageBucket: 'partymanagement-3e485.firebasestorage.app',
    measurementId: 'G-6VGX6WHQNT',
  );
}
